services:
  - type: worker          # proceso en background (NO web server)
    name: ml-ofertas-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false       # lo introduces manualmente en el dashboard
      - key: CHAT_ID
        sync: false
      - key: AFFILIATE_LINK
        sync: false
