services:
  - type: web             # Web Service (tiene port binding, no se cae como worker)
    name: ml-ofertas-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: AFFILIATE_LINK
        sync: false
